apply plugin: 'com.android.application'
android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"
    defaultConfig {
        applicationId "com.enjoy.wanji"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 16
        versionName "1.2.43"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
//    //解决高德地图和视频x86冲突问题
    repositories {
        flatDir {
            dirs 'libs'
        }
    }
    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            def project ="智驾终端"
            output.outputFileName = "${project}-${variant.versionName}.apk"
        }
    }

}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    implementation files('libs/AMap3DMap_10.1.300_AMapSearch_9.7.4_AMapLocation_6.4.9_20250509.jar')
//    用于Them.AppCompat
    implementation 'com.android.support:appcompat-v7:24.2.1'
    implementation 'com.google.code.gson:gson:2.7'
    implementation 'org.zeromq:jeromq:0.3.6'
    testImplementation 'junit:junit:4.12'
    implementation files('libs/json-simple-1.1.jar')
    implementation files('libs/java_websocket.jar')
    implementation 'org.rajawali3d:rajawali:1.2.1970'
}
